### ISSUE TITLE
Create gist failure

### ISSUE THREAD

**Issue by fonnesbeck** [hiltmon/Gist.tmbundle#2]
Beginning a few weeks ago, I am no longer able to create gists, either public or private, using this bundle. Each time, I get the following error. Note, however, that updating an existing gist from TextMate works fine.

```
/Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:359:in `read': No such file or directory - 3. Plotting and Visualization.ipynb (Errno::ENOENT)
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:359:in `make_data'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:355:in `each'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:355:in `make_data'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:331:in `api_post_request'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:180:in `create_gist'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:161:in `create'
    from Create Public Gist:8
```

**Comment by hiltmon** [comment]
Wow, thanks for spotting this Chris.

I have updated the bundle to use the full path for creating gist files -- for some reason I stupidly stripped the path in the last update. Humblest apologies.

Please update and let me know if it is working again for you.

~Hilton

**Comment by fonnesbeck** [comment]
This seems to work now. Thanks again for a very useful bundle!

**Comment by fonnesbeck** [comment]
This appears to have arisen again, but in different form. I get the following error:

```
ruby: warning: -K is specified; it is for 1.8 compatibility and may cause odd behavior
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb:101: warning: assigned but unused variable - id
/Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:145: warning: assigned but unused variable - pid
/Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/progress.rb:57: warning: shadowing outer local variable - params
/Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/progress.rb:55: warning: assigned but unused variable - ui_process
/Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:308:in `to_plist': An object in the argument tree could not be converted (ArgumentError)
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:308:in `block in initialize'
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:307:in `popen'
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:307:in `initialize'
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:20:in `new'
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/ui.rb:20:in `dialog'
    from /Users/fonnescj/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/lib/progress.rb:42:in `call_with_progress'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:344:in `api_post_request'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:180:in `create_gist'
    from /Users/fonnescj/Library/Application Support/Avian/Bundles/Gist.tmbundle/Support/bin/gistmate.rb:161:in `create'
    from Create Private Gist:8:in `<main>'
```

And then I get a blank window that persists after the error:

![screen shot 2013-10-27 at 12 36 26 pm](https://f.cloud.github.com/assets/81476/1416306/b050de5a-3f47-11e3-97a8-39107814df72.png)

**Comment by hiltmon** [comment]
Chris

Can you confirm for me:
- Operating System version
- Textmate Version

If you have upgraded to Mavericks, then make a copy of the bundle and according to Allan:

> If you wish to use TextMate 1.x on OS X 10.9 then to fix bundle items that do not work with ruby 2.0 you will need to open the bundle editor and change the first line of the command (called shebang) to the following:
> 
> #!/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
> 
> More info about editing commands here https://manual.macromates.com/en/commands

If that works for you, I'll make that change permanent

~Hilton

**Comment by fonnesbeck** [comment]
I'm running Textmate 2 (2.0-alpha.9491) on OS X 10.9.

**Comment by fonnesbeck** [comment]
Yeah, changing the ruby appeared to do the trick.

**Comment by hiltmon** [comment]
Ok, pushed the 1.8 hack for now.

**Comment by fonnesbeck** [comment]
I'm getting way ahead here, I know, but of course upgrading to Yosemite breaks this because Ruby is now 2.0.

**Comment by fonnesbeck** [comment]
Yeah, it looks like Yosemite does not have ruby 1.8 at all.

**Comment by hiltmon** [comment]
Yep, I see that. Also looks like the built-in TextMate 2 UI and bundle support modules, needed to pick and display Gists are dependent on Ruby 1.8. They have a patch (not yet released) that installs a Ruby 1.8 for TM2 if it's not found. Until they fix the bundle support for Ruby 2+ (or release the 1.8 installer), this bundle will continue to fail. Wish I could give you a better answer. ~Hilton

**Comment by fonnesbeck** [comment]
Thanks for the info. I will wait patiently.

**Comment by hiltmon** [comment]
Michael Sheets from TextMate fixed it, brilliant! Either pull this repo or wait until they push the new bundle out. ~Hilton
