### ISSUE TITLE
Message: Failed: 401: {message:Must

### ISSUE THREAD

**Issue by quinncomendant** [hiltmon/Gist.tmbundle#8]
When attempting to run `Gist from Selection` I momentarily see "Creating New Unchached Gist…" and then this error dialog:

```
Abort Message
Message: Failed: 401: {message:Must
```

Unfortunately the message is truncated at "Must" so I don't know what important message it's trying to tell me. Do you know what is wrong?

**Comment by lambdamusic** [comment]
I'm getting the same error message

**Comment by loranger** [comment]
Yep, me too

Maybe a two-factor issue ?

**Comment by kroo** [comment]
Getting this error too–it is indeed a two-factor issue.  After fixing the truncation issue, the full text of this error is:

```
Message: Failed: 401: {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
```

**Comment by kroo** [comment]
To fix this issue, [use a "personal access token"](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) as the value of `github.password` in your git config (as recommended by the [two-factor authentication github api documentation](https://developer.github.com/v3/auth/#working-with-two-factor-authentication)).

Aka:
1. Follow this article to get an access token: https://help.github.com/articles/creating-an-access-token-for-command-line-use/
2. Run the following via Terminal (replacing `[access_token]` with the access token acquired in the previous step:
   
   ``` sh
   git config --global github.password [access_token]
   ```

**Comment by quinncomendant** [comment]
I had assigned my access_token to the `github.token` config option. It works if I move the access_token to `github.password` as you've recommended. Go figure. ¯_(ツ)_/¯

I notice the error message displays something useful now. Thanks
